"""Workbench 所需的只读 evidence 与后台任务端口。"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from agent_forge.workbench.domain.models import WorkbenchCommand, WorkbenchJob


class EvidenceCatalogPort(Protocol):
    def latest_run_dir(self) -> Path | None: ...
    def latest_report_path(self) -> str: ...
    def read_latest_report(self) -> str: ...
    def latest_trace_path(self) -> Path | None: ...
    def latest_usage_path(self) -> Path | None: ...
    def latest_comparison_path(self) -> Path | None: ...
    def latest_multi_agent_summary_path(self) -> Path | None: ...
    def latest_fanout_summary_path(self) -> Path | None: ...
    def trace_paths(self) -> list[tuple[str, Path]]: ...
    def latest_feedback_path(self) -> Path | None: ...
    def latest_feedback_outcome(self) -> str: ...
    def latest_result_record(self) -> dict[str, Any]: ...
    def latest_direct_baseline_record(self) -> dict[str, Any]: ...


class BackgroundJobsPort(Protocol):
    def start_job(self, command: WorkbenchCommand) -> WorkbenchJob: ...
    def get_job(self, job_id: str) -> WorkbenchJob | None: ...
    def latest_jobs(self) -> list[WorkbenchJob]: ...
