"""Workbench 所需的只读 evidence 端口。"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from agent_forge.observability.domain.run_story import RunStory


class EvidenceCatalogPort(Protocol):
    def latest_run_dir(self) -> Path | None: ...
    def latest_run_story(self) -> RunStory | None: ...
    def latest_report_path(self) -> str: ...
    def read_latest_report(self) -> str: ...
    def latest_trace_path(self) -> Path | None: ...
    def latest_usage_path(self) -> Path | None: ...
    def latest_comparison_path(self) -> Path | None: ...
    def latest_multi_agent_summary_path(self) -> Path | None: ...
    def latest_fanout_summary_path(self) -> Path | None: ...
    def trace_paths(self) -> list[tuple[str, Path]]: ...
    def latest_feedback_path(self) -> Path | None: ...
    def latest_feedback_outcome(self) -> str: ...
    def latest_result_record(self) -> dict[str, Any]: ...
    def latest_direct_baseline_record(self) -> dict[str, Any]: ...
    def latest_campaign_dir(self) -> Path | None: ...
    def latest_campaign_state(self) -> dict[str, Any]: ...
    def latest_campaign_summary(self) -> dict[str, Any]: ...
